# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - jokes-service-giithub-2

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_e70170faf21c434187523934e4c4a3a5 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_746f47c8bffa43bc97ef5ccf3b8de1ce }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_e70170faf21c434187523934e4c4a3a5 }}/jokes-service-new:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'jokes-service-giithub-2'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4fbb6316881f48368fafaef1d6f578d4 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_e70170faf21c434187523934e4c4a3a5 }}/jokes-service-new:${{ github.sha }}'